### ISSUE TITLE
Can't parse formulas when encounter # 

### ISSUE THREAD

**Issue by flyaway1217** [akfish/hexo-math#25]
When I put "#" symbol into latex code, Hexo got a error like this: 
Error: unexpected end of comment
    at Tokenizer.nextToken (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/lexer.js:268:31)
    at Object.extend.nextToken (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:32:27)
    at Object.extend.parseNodes (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1121:27)
    at Object.extend.parse (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1173:46)
    at Object.extend.parseUntilBlocks (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1111:24)
    at NunjucksBlock._parseBody (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:111:21)
    at NunjucksBlock.parse (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:105:19)
    at Object.extend.parseStatement (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:540:36)
    at Object.extend.parseNodes (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1151:30)
    at Object.extend.parseAsRoot (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:70:37)
    at Tag.render (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/flyaway/workspace/Blog/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
FATAL Error: unexpected end of comment
    at Tokenizer.nextToken (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/lexer.js:268:31)
    at Object.extend.nextToken (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:32:27)
    at Object.extend.parseNodes (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1121:27)
    at Object.extend.parse (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1173:46)
    at Object.extend.parseUntilBlocks (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1111:24)
    at NunjucksBlock._parseBody (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:111:21)
    at NunjucksBlock.parse (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:105:19)
    at Object.extend.parseStatement (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:540:36)
    at Object.extend.parseNodes (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1151:30)
    at Object.extend.parseAsRoot (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1177:42)
    at Object.module.exports.parse (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/parser.js:1199:18)
    at Object.module.exports.compile (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/compiler.js:1118:48)
    at Obj.extend._compile (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:444:35)
    at Obj.extend.compile (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:433:18)
    at null.<anonymous> (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:378:22)
    at Object.exports.withPrettyErrors (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
    at Obj.extend.render (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
    at /Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:56:9
    at tryCatcher (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:70:37)
    at Tag.render (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/extend/tag.js:55:10)
    at Object.tagFilter [as onRenderEnd] (/Users/flyaway/workspace/Blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/flyaway/workspace/Blog/node_modules/hexo/lib/hexo/render.js:55:19
    at tryCatcher (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/flyaway/workspace/Blog/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

The code is: 

{% math %}
\begin{equation}
P(w_i\vert w_{i-1}) = \frac{P(w_i,w_{i-1})}{P(w_{i-1})} = \frac{\frac{\# (x_{i-1},x_i)}{\# }}{\frac{\# w_{i-1}}{\#}} = \frac{\#(x_{i-1},x_i)}{\# w_{i-1}}
\end{equation}
{% endmath %}

I am not sure which one cause the problem, hexo itself or hexo-math. 
This same code can show the formulas in the demo page of MathJax.

**Comment by akfish** [comment]
It's a Hexo issue. Built in tags will fail too:
```
{% blockquote %}
{#}
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit lacus ut purus iaculis feugiat. Sed nec tempor elit, quis aliquam neque. Curabitur sed diam eget dolor fermentum semper at eu lorem.
{% endblockquote %}
```

Hexo uses nunjucks to implement tags. And the syntax in question is in conflict with nunjuncks [comments][1] syntax.

Adding spaces between `{` and `#` seems to fix the problem:

```
{% math %}
\begin{equation}
P(w_i\vert w_{i-1}) = \frac{P(w_i,w_{i-1})}{P(w_{i-1})} = \frac{\frac{ # (x_{i-1},x_i)}{ # }}{\frac{ # w_{i-1}}{ # }} = \frac{ #(x_{i-1},x_i) }{ # w_{i-1}}
\end{equation}
{% endmath %}
```

[1]: https://mozilla.github.io/nunjucks/templating.html#comments

**Comment by flyaway1217** [comment]
Thx! It seems to be a good solution to this issue.


flyaway

**Comment by akfish** [comment]
No problem.
