### ISSUE TITLE
No method 'parse'

### ISSUE THREAD

**Issue by kenkangxgwe** [akfish/hexo-math#35]
I installed hexo-math v3.0.2, but the message below keeps jump out no matter what command I execute that start with `hexo`
```
INFO  [hexo-inject] installing hotfix for hexojs/hexo#1791
INFO  [hexo-math] Using engine 'mathjax'
Unhandled rejection TypeError: Object [object Object] has no method 'parse'
    at parse (/home/server/blog/node_modules/hexo-inject/lib/util.js:40:31)
    at Array.map (native)
    at callsite (/home/server/blog/node_modules/hexo-inject/lib/util.js:52:4)
    at Inject.require (/home/server/blog/node_modules/hexo-inject/lib/mixin/require.js:100:55)
    at Object.require (/home/server/blog/node_modules/hexo-inject/lib/inject.js:65:21)
    at Inject._injectMathJax (/home/server/blog/node_modules/hexo-math/lib/filter/inject.js:43:22)
    at Hexo.tryCatcher (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/lc-server/blog/node_modules/hexo/lib/extend/filter.js:68:35
    at tryCatcher (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromiseCtx (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Async._drainQueue (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/server/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)
```
Do you have any idea?

**Comment by kenkangxgwe** [comment]
I found that my nodejs version is too low. Upgrade to the latest stable version solve the problem.
