### ISSUE TITLE
Example 中的 Tag-inline 无法使用

### ISSUE THREAD

**Issue by hcoona** [akfish/hexo-math#5]
hexo-math 文档中给出了四种 Example，只有其中的 Tag-inline 的例子无法使用，错误信息如下：

	Template render error: SyntaxError: Unexpected token ILLEGAL
	    at null.<anonymous> (/Users/zhangshuai/test-hexo-math/node_modules/hexo-math/bin/index.js:45:39)
	    at NunjucksTag._run (/Users/zhangshuai/test-hexo-math/node_modules/hexo/lib/extend/tag.js:94:18)

我不太了解 hexo 不知道是哪里有问题，复现步骤：

1. hexo init test-hexo-math
2. cd test-hexo-math
3. npm install
4. npm install --save hexo-math
5. hexo math install
6. hexo new test-math
7. 编辑 `source/_posts/test-math.md`
8. hexo server

`test-main.md` 中的内容如下：

	## Tag inline:

	This equation {% math \cos 2\theta = \cos^2 \theta - \sin^2 \theta =  2 \cos^2 \theta - 1 %} is inline.

完整报错信息如下：

    ➜ test-hexo-math hexo server
    FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
    Template render error: SyntaxError: Unexpected token ILLEGAL
        at null.<anonymous> (/Users/zhangshuai/test-hexo-math/node_modules/hexo-math/bin/index.js:45:39)
        at NunjucksTag._run (/Users/zhangshuai/test-hexo-math/node_modules/hexo/lib/extend/tag.js:94:18)
        at NunjucksTag.run (/Users/zhangshuai/test-hexo-math/node_modules/hexo/lib/extend/tag.js:90:15)
        at root [as rootRenderFunc] (eval at <anonymous> (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/nunjucks/src/environment.js:450:24), <anonymous>:8:64)
        at null.<anonymous> (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/nunjucks/src/environment.js:387:18)
        at Object.exports.withPrettyErrors (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/nunjucks/src/lib.js:24:16)
        at Obj.extend.render (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/nunjucks/src/environment.js:374:20)
        at Obj.extend.renderString (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/nunjucks/src/environment.js:261:21)
        at /Users/zhangshuai/test-hexo-math/node_modules/hexo/lib/extend/tag.js:56:9
        at tryCatcher (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
        at Promise._resolveFromResolver (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/promise.js:427:31)
        at new Promise (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/promise.js:53:37)
        at Tag.render (/Users/zhangshuai/test-hexo-math/node_modules/hexo/lib/extend/tag.js:55:10)
        at /Users/zhangshuai/test-hexo-math/node_modules/hexo/lib/hexo/post.js:320:16
        at tryCatcher (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
        at Promise._settlePromiseFromHandler (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
        at Promise._settlePromiseAt (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
        at Async._drainQueue (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/async.js:180:12)
        at Async._drainQueues (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/async.js:185:10)
        at Immediate.Async.drainQueues [as _onImmediate] (/Users/zhangshuai/test-hexo-math/node_modules/hexo/node_modules/bluebird/js/main/async.js:15:14)
        at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by hcoona** [comment]
补充一下环境信息

* `hexo-math@1.0.5`
* `uname -a`：

        Darwin zhangshuaideMac-mini.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

* `hexo --version`：

        hexo: 3.0.1
        os: Darwin 14.3.0 darwin x64
        http_parser: 2.3
        node: 0.12.2
        v8: 3.28.73
        uv: 1.4.2-node1
        zlib: 1.2.8
        modules: 14
        openssl: 1.0.1m

**Comment by akfish** [comment]
在Win7和Ubuntu上用Hexo 3.0.1测试正常，不能重现故障。
手里没有Mac系统，无法用完全一样的环境测试。
`bin/index.js`是从`src/index.coffee`编译生成的，可能是由于文件在传输过程中损坏或者编码问题。

可以尝试下卸载hexo-math后再重装，不行的话再试试在本地重新编译，步骤如下：
1. `npm install -g coffee-script`
2. `cd /Users/zhangshuai/test-hexo-math/node_modules/hexo-math/`
3. `cake build`

**Comment by hcoona** [comment]
重新开目录用 nano 粘贴示例代码解决，谢谢！
